# Generated by Django 6.0.6 on 2026-06-20 14:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('PERCENTAGE', 'Percentage Based'), ('FIXED', 'Fixed Cash Value'), ('PH_SPECIAL', 'Philippine Statutory (Senior/PWD)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage value or exact cash deduction amount.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Barcode')),
                ('emoji', models.CharField(blank=True, help_text='Emoji for visual display (e.g., 🍗🍚🥤)', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image (optional, emoji used as fallback)', null=True, upload_to='product_images/')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_exclusive_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital Wallet (GCash/Maya)')], default='CASH', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Trace ID for GCash/Maya validation', max_length=100, null=True)),
                ('total_diners', models.PositiveIntegerField(default=1)),
                ('special_cardholders_count', models.PositiveIntegerField(default=0)),
                ('discount_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.discounttype')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='pos.transaction')),
            ],
        ),
    ]
