# Generated by Django 6.0.6 on 2026-06-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('emoji', models.CharField(blank=True, default='', help_text='Emoji for visual display (e.g., 🍗🍚🥤)', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'meal subcategories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='meal_subcategory',
            field=models.ForeignKey(blank=True, help_text='Food group/meal subcategory for POS product filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='pos.mealsubcategory'),
        ),
    ]
