# Generated by Django 6.0.6 on 2026-06-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_seed_mealsubcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='table_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dining table number (1-20), null for takeout', null=True),
        ),
    ]
