# Generated by Django 6.0.6 on 2026-06-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_transaction_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out')], default='DINE_IN', help_text='Order fulfillment type: DINE_IN or TAKE_OUT', max_length=10),
        ),
    ]
