# Generated by Django 6.0.6 on 2026-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_transaction_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vat_inclusive',
            field=models.BooleanField(default=True, help_text='Whether 12% VAT is applied to this transaction'),
        ),
    ]
