# Generated by Django 6.0.6 on 2026-06-22 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_transaction_vat_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual percentage discount (0-100%) applied to subtotal', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
