# Generated by Django 6.0.6 on 2026-06-22 14:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_shift_transaction_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_value', models.DecimalField(decimal_places=2, help_text='Denomination value (e.g., 1000.00, 500.00, 100.00, 50.00, 20.00)', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-computed: denomination_value * quantity', max_digits=10)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='pos.shift')),
            ],
            options={
                'verbose_name_plural': 'cash counts',
            },
        ),
    ]
