# Generated by Django 3.2 on 2026-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='void_reason',
            field=models.TextField(blank=True, null=True, help_text='Reason for voiding the transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, help_text='When the transaction was voided'),
        ),
    ]
