# Generated by Django 6.0.6 on 2026-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_transaction_void_reason_voided_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fb_psid', models.CharField(help_text='Facebook Messenger PSID for chatbot conversations', max_length=255, unique=True)),
                ('remarks', models.TextField(blank=True, help_text='Operational clinic remarks visible to LLM but not revealed verbatim to patient', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
