# Generated by Django 6.0.6 on 2026-06-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('served', 'Served'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('service', models.CharField(blank=True, default='', help_text='Service requested (e.g., Check-up, Lab, X-Ray)', max_length=255)),
                ('service_area', models.CharField(blank=True, default='', help_text='Clinic area/room where service is provided', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the queue entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='pos.patient')),
            ],
            options={
                'verbose_name_plural': 'queue entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
