# Generated by Django 6.0.6 on 2026-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('LPG', 'LPG'), ('AGRI', 'AGRI'), ('GAS', 'GAS')], max_length=10)),
                ('code', models.CharField(help_text='Short branch code (e.g., LPG-01, AGRI-01)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Default tax rate %', max_digits=5)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
    ]
