# Generated by Django 6.0.6 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_item_branch_shift_branch_staff_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('LPG', 'LPG Refilling Station'), ('AGRI', 'Agricultural Supply'), ('GAS', 'Gas Station'), ('RETAIL', 'Retail Store'), ('WHOLESALE', 'Wholesale'), ('SERVICE', 'Service Business'), ('MANUFACTURING', 'Manufacturing'), ('FOOD', 'Food & Restaurant'), ('HEALTH', 'Health & Pharmacy'), ('EDUCATION', 'Education'), ('TRANSPORT', 'Transport & Logistics'), ('CONSTRUCTION', 'Construction'), ('TECH', 'Technology'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
