# Generated by Django 6.0.6 on 2026-07-18 06:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_branch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Product description / details', null=True),
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size label (e.g., 11kg, Small, 1L, XL)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price for this size', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Retail price (falls back to price if not set)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pos.item')),
            ],
            options={
                'verbose_name_plural': 'item sizes',
                'ordering': ['item', 'name'],
                'unique_together': {('item', 'name')},
            },
        ),
    ]
