# Generated by Django 6.0.6 on 2026-07-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_item_description_itemsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('date_borrowed', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='borrower_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='pos.branch')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to='pos.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
